# Generated by Django 6.0.1 on 2026-03-30 09:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0002_job_completed_at_job_deadline_job_site_address_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Certificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("completion_certificate", "Completion Certificate"),
                            ("work_agreement", "Work Agreement"),
                        ],
                        default="completion_certificate",
                        max_length=50,
                    ),
                ),
                ("certificate_number", models.CharField(max_length=40, unique=True)),
                ("subject_name", models.CharField(max_length=255)),
                ("issued_to_role", models.CharField(max_length=20)),
                ("body_text", models.TextField()),
                ("issued_at", models.DateTimeField(auto_now_add=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificates",
                        to="jobs.job",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "certificates",
                "ordering": ["-issued_at"],
                "unique_together": {("job", "recipient", "document_type")},
            },
        ),
    ]
