# Generated by Django 6.0.1 on 2026-04-08 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0004_fix_review_constraint"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="site_latitude",
        ),
        migrations.RemoveField(
            model_name="job",
            name="site_longitude",
        ),
    ]
