# Generated by Django 6.0.1 on 2026-04-08 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_bio_user_is_verified_user_latitude_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="verification_document_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Aadhaar", "Aadhaar"),
                    ("PAN Card", "PAN Card"),
                    ("Voter ID", "Voter ID"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
