# Generated by Django 6.0.1 on 2026-04-08 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_user_date_of_birth_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="latitude",
        ),
        migrations.RemoveField(
            model_name="user",
            name="longitude",
        ),
    ]
