# Generated by Django 6.0.1 on 2026-04-08 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_passkeycredential"),
        ("accounts", "0004_remove_user_latitude_remove_user_longitude"),
    ]

    operations = []
