from django.core.mail import EmailMessage
from django.db.models import Avg, Count, Q
from django.http import HttpResponse
from django.utils import timezone
from rest_framework import status, viewsets
from rest_framework.decorators import api_view, permission_classes, action
from rest_framework.response import Response
from rest_framework.permissions import IsAuthenticated
from rest_framework.views import APIView
from django.db import transaction
from django.db.models import F
from .models import Job, Application, AttendanceRecord, WorkerAvailability, Review, Certificate
from .serializers import (
    JobCreateSerializer,
    JobListSerializer,
    ApplicationSerializer,
    ApplicationStatusUpdateSerializer,
    AttendanceRecordSerializer,
    WorkerAvailabilitySerializer,
    ReviewSerializer,
    TaskCoworkerSerializer,
    CertificateSerializer,
)
from accounts.permissions import IsWorker, IsEmployer, IsEmployerOrAdmin


def _build_certificate_text(job, recipient, role_label):
    start_date = job.start_date.isoformat() if job.start_date else 'Not specified'
    deadline = job.deadline.isoformat() if job.deadline else 'Not specified'
    completed = timezone.localtime(job.completed_at).strftime('%Y-%m-%d %H:%M') if job.completed_at else 'Pending'
    return (
        'WORKSITE COMPLETION CERTIFICATE\n'
        f'Job: {job.title}\n'
        f'Recipient: {recipient.full_name}\n'
        f'Role: {role_label}\n'
        f'Employer: {job.employer.full_name}\n'
        f'Site: {job.site_address or job.site_city or "Not specified"}\n'
        f'Start Date: {start_date}\n'
        f'Deadline: {deadline}\n'
        f'Completed At: {completed}\n'
        f'Required Workers: {job.required_workers}\n'
        f'Filled Slots: {job.filled_slots}\n'
        '\n'
        'This document certifies that the above WorkSite engagement was completed and recorded in the platform.\n'
    )


def _issue_completion_certificates(job):
    accepted_workers = list(
        Application.objects.filter(job=job, status='accepted').select_related('worker')
    )
    recipients = [(job.employer, 'employer')]
    recipients.extend((application.worker, 'worker') for application in accepted_workers)

    issued = []
    for recipient, role_label in recipients:
        certificate_number = f'WS-{job.id}-{recipient.id}-CC'
        body_text = _build_certificate_text(job, recipient, role_label)
        certificate, created = Certificate.objects.get_or_create(
            job=job,
            recipient=recipient,
            document_type='completion_certificate',
            defaults={
                'certificate_number': certificate_number,
                'subject_name': job.title,
                'issued_to_role': role_label,
                'body_text': body_text,
            },
        )
        if created:
            email = EmailMessage(
                subject=f'WorkSite completion certificate for {job.title}',
                body='Your completion certificate is attached. This email was generated by WorkSite.',
                to=[recipient.email],
            )
            email.attach(
                f'{certificate.certificate_number}.txt',
                certificate.body_text,
                'text/plain',
            )
            email.send(fail_silently=True)
        issued.append(certificate)
    return issued


class JobViewSet(viewsets.ModelViewSet):
    """ViewSet for job management"""
    queryset = Job.objects.select_related('employer').prefetch_related('applications__worker').all()
    permission_classes = [IsAuthenticated]
    
    def get_serializer_class(self):
        """Return appropriate serializer class"""
        if self.action == 'create':
            return JobCreateSerializer
        return JobListSerializer
    
    def get_permissions(self):
        """Set permissions based on action"""
        if self.action == 'create':
            return [IsEmployer()]
        elif self.action in ['destroy', 'update', 'partial_update']:
            return [IsEmployerOrAdmin()]
        return [IsAuthenticated()]
    
    def get_queryset(self):
        """Filter queryset based on query parameters"""
        queryset = super().get_queryset()

        user = self.request.user
        status_filter = self.request.query_params.get('status')
        if status_filter:
            queryset = queryset.filter(status=status_filter)
        elif user.role == 'worker':
            queryset = queryset.filter(status='open') | queryset.filter(applications__worker=user)

        city = self.request.query_params.get('city')
        if city:
            queryset = queryset.filter(employer__city=city)

        site_city = self.request.query_params.get('site_city')
        if site_city:
            queryset = queryset.filter(site_city__iexact=site_city)

        min_wage = self.request.query_params.get('min_wage')
        if min_wage:
            queryset = queryset.filter(daily_wage__gte=min_wage)

        max_wage = self.request.query_params.get('max_wage')
        if max_wage:
            queryset = queryset.filter(daily_wage__lte=max_wage)

        skill = self.request.query_params.get('skill')
        if skill:
            queryset = queryset.filter(skills_required__icontains=skill)

        if user.role == 'employer':
            my_jobs = self.request.query_params.get('my_jobs')
            if my_jobs == 'true':
                queryset = queryset.filter(employer=user)

        return queryset.distinct().order_by('-created_at')
    
    def perform_create(self, serializer):
        """Create job with current user as employer"""
        serializer.save(employer=self.request.user)
    
    def destroy(self, request, *args, **kwargs):
        """Delete job - only owner or admin"""
        job = self.get_object()
        
        # Check if user is owner or admin
        if job.employer != request.user and request.user.role != 'admin':
            return Response({
                'error': 'You do not have permission to delete this job'
            }, status=status.HTTP_403_FORBIDDEN)
        
        job.delete()
        return Response({
            'message': 'Job deleted successfully'
        }, status=status.HTTP_204_NO_CONTENT)
    
    @action(detail=True, methods=['post'], permission_classes=[IsWorker])
    def apply(self, request, pk=None):
        """Apply for a job - atomic operation to prevent race conditions"""
        job = self.get_object()
        
        # Use transaction to ensure atomicity
        try:
            with transaction.atomic():
                # Lock the job row for update
                job = Job.objects.select_for_update().get(pk=job.pk)
                
                # Check if job is still open
                if job.status == 'closed':
                    return Response({
                        'error': 'This job is no longer accepting applications'
                    }, status=status.HTTP_400_BAD_REQUEST)
                
                # Check if slots are available
                if job.filled_slots >= job.required_workers:
                    job.status = 'closed'
                    job.save()
                    return Response({
                        'error': 'All positions have been filled'
                    }, status=status.HTTP_400_BAD_REQUEST)
                
                # Check for duplicate application
                if Application.objects.filter(job=job, worker=request.user).exists():
                    return Response({
                        'error': 'You have already applied for this job'
                    }, status=status.HTTP_400_BAD_REQUEST)
                
                # Create application
                application = Application.objects.create(
                    job=job,
                    worker=request.user,
                    status='pending'
                )
                
                # Note: filled_slots is incremented when application is accepted
                # not when application is submitted
                
                return Response({
                    'message': 'Application submitted successfully',
                    'application': ApplicationSerializer(application).data
                }, status=status.HTTP_201_CREATED)
                
        except Job.DoesNotExist:
            return Response({
                'error': 'Job not found'
            }, status=status.HTTP_404_NOT_FOUND)
        except Exception as e:
            return Response({
                'error': f'Failed to submit application: {str(e)}'
            }, status=status.HTTP_500_INTERNAL_SERVER_ERROR)
    
    @action(detail=True, methods=['get'], permission_classes=[IsEmployerOrAdmin])
    def applications(self, request, pk=None):
        """Get all applications for a job"""
        job = self.get_object()
        
        # Check if user is job owner or admin
        if job.employer != request.user and request.user.role != 'admin':
            return Response({
                'error': 'You do not have permission to view these applications'
            }, status=status.HTTP_403_FORBIDDEN)
        
        applications = job.applications.select_related('worker').all()
        serializer = ApplicationSerializer(applications, many=True)
        return Response(serializer.data, status=status.HTTP_200_OK)


@api_view(['PUT'])
@permission_classes([IsEmployerOrAdmin])
def update_application_status(request):
    """Update application status (accept/reject)"""
    application_id = request.data.get('application_id')
    new_status = request.data.get('status')
    
    if not application_id or not new_status:
        return Response({
            'error': 'application_id and status are required'
        }, status=status.HTTP_400_BAD_REQUEST)
    
    serializer = ApplicationStatusUpdateSerializer(data={'status': new_status})
    if not serializer.is_valid():
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)
    
    try:
        with transaction.atomic():
            application = Application.objects.select_related('job').select_for_update().get(
                id=application_id
            )
            
            # Check if user is the job employer
            if application.job.employer != request.user and request.user.role != 'admin':
                return Response({
                    'error': 'You do not have permission to modify this application'
                }, status=status.HTTP_403_FORBIDDEN)
            
            # Check if job is closed
            if application.job.status == 'closed' and new_status == 'accepted':
                return Response({
                    'error': 'Cannot accept applications for a closed job'
                }, status=status.HTTP_400_BAD_REQUEST)
            
            old_status = application.status
            application.status = new_status
            
            # If accepting, increment filled_slots atomically
            if new_status == 'accepted' and old_status != 'accepted':
                job = Job.objects.select_for_update().get(pk=application.job.pk)
                
                # Check if there are available slots
                if job.filled_slots >= job.required_workers:
                    return Response({
                        'error': 'All positions have been filled'
                    }, status=status.HTTP_400_BAD_REQUEST)
                
                # Increment filled_slots using F() to prevent race conditions
                Job.objects.filter(pk=job.pk).update(
                    filled_slots=F('filled_slots') + 1
                )
                job.refresh_from_db()
                
                # Auto-close job if all slots are filled
                if job.filled_slots >= job.required_workers:
                    job.status = 'closed'
                    job.save()
            
            # If rejecting a previously accepted application, decrement filled_slots
            elif old_status == 'accepted' and new_status == 'rejected':
                Job.objects.filter(pk=application.job.pk).update(
                    filled_slots=F('filled_slots') - 1,
                    status='open'  # Reopen job if it was closed
                )
            
            application.save()
            
            return Response({
                'message': f'Application {new_status} successfully',
                'application': ApplicationSerializer(application).data
            }, status=status.HTTP_200_OK)
            
    except Application.DoesNotExist:
        return Response({
            'error': 'Application not found'
        }, status=status.HTTP_404_NOT_FOUND)
    except Exception as e:
        return Response({
            'error': f'Failed to update application: {str(e)}'
        }, status=status.HTTP_500_INTERNAL_SERVER_ERROR)


@api_view(['DELETE'])
@permission_classes([IsEmployerOrAdmin])
def remove_worker_from_job(request, job_id, worker_id):
    """Remove a worker from a job"""
    try:
        with transaction.atomic():
            job = Job.objects.select_for_update().get(pk=job_id)
            
            # Check if user is the job employer
            if job.employer != request.user and request.user.role != 'admin':
                return Response({
                    'error': 'You do not have permission to modify this job'
                }, status=status.HTTP_403_FORBIDDEN)
            
            # Find the application
            application = Application.objects.get(job=job, worker_id=worker_id)
            
            # If application was accepted, decrement filled_slots
            if application.status == 'accepted':
                Job.objects.filter(pk=job.pk).update(
                    filled_slots=F('filled_slots') - 1,
                    status='open'
                )
            
            # Delete the application
            application.delete()
            
            return Response({
                'message': 'Worker removed from job successfully'
            }, status=status.HTTP_204_NO_CONTENT)
            
    except Job.DoesNotExist:
        return Response({
            'error': 'Job not found'
        }, status=status.HTTP_404_NOT_FOUND)
    except Application.DoesNotExist:
        return Response({
            'error': 'Application not found'
        }, status=status.HTTP_404_NOT_FOUND)
    except Exception as e:
        return Response({
            'error': f'Failed to remove worker: {str(e)}'
        }, status=status.HTTP_500_INTERNAL_SERVER_ERROR)


@api_view(['GET'])
@permission_classes([IsWorker])
def my_applications(request):
    """Get current user's applications"""
    applications = Application.objects.filter(worker=request.user).select_related('job', 'job__employer')
    serializer = ApplicationSerializer(applications, many=True)
    return Response(serializer.data, status=status.HTTP_200_OK)


class WorkerAvailabilityViewSet(viewsets.ModelViewSet):
    """Workers can manage their own calendar entries."""

    serializer_class = WorkerAvailabilitySerializer
    permission_classes = [IsWorker]

    def get_queryset(self):
        queryset = WorkerAvailability.objects.filter(worker=self.request.user)
        start_date = self.request.query_params.get('start_date')
        end_date = self.request.query_params.get('end_date')

        if start_date:
            queryset = queryset.filter(end_date__gte=start_date)
        if end_date:
            queryset = queryset.filter(start_date__lte=end_date)

        return queryset.order_by('start_date', 'end_date')

    def perform_create(self, serializer):
        serializer.save(worker=self.request.user)


class ReviewViewSet(viewsets.ModelViewSet):
    """Mutual feedback between employers and workers."""

    serializer_class = ReviewSerializer
    permission_classes = [IsAuthenticated]

    def get_queryset(self):
        queryset = Review.objects.select_related('job', 'reviewer', 'reviewee')
        user = self.request.user
        mine = self.request.query_params.get('mine')
        reviewee_id = self.request.query_params.get('reviewee')
        job_id = self.request.query_params.get('job')

        if mine == 'true':
            queryset = queryset.filter(Q(reviewer=user) | Q(reviewee=user))
        if reviewee_id:
            queryset = queryset.filter(reviewee_id=reviewee_id)
        if job_id:
            queryset = queryset.filter(job_id=job_id)
        return queryset

    def create(self, request, *args, **kwargs):
        serializer = self.get_serializer(data=request.data)
        serializer.is_valid(raise_exception=True)

        job = serializer.validated_data['job']
        reviewee = serializer.validated_data['reviewee']
        reviewer = request.user

        if reviewer == reviewee:
            return Response({'error': 'You cannot review yourself'}, status=status.HTTP_400_BAD_REQUEST)

        accepted_application = Application.objects.filter(
            job=job,
            worker=reviewee if reviewee.role == 'worker' else reviewer,
            status='accepted',
        ).exists()

        is_valid_pair = (
            reviewer == job.employer and reviewee.role == 'worker'
        ) or (
            reviewee == job.employer and reviewer.role == 'worker'
        )

        if not is_valid_pair or not accepted_application:
            return Response({
                'error': 'Reviews are only allowed between the employer and accepted workers for that job'
            }, status=status.HTTP_400_BAD_REQUEST)

        review = serializer.save(reviewer=reviewer)
        output = self.get_serializer(review)
        return Response(output.data, status=status.HTTP_201_CREATED)


class AttendanceRecordView(APIView):
    permission_classes = [IsEmployerOrAdmin]

    def post(self, request, job_id):
        try:
            job = Job.objects.get(pk=job_id)
        except Job.DoesNotExist:
            return Response({'error': 'Job not found'}, status=status.HTTP_404_NOT_FOUND)

        if job.employer != request.user and request.user.role != 'admin':
            return Response({'error': 'You do not have permission to mark attendance'}, status=status.HTTP_403_FORBIDDEN)

        serializer = AttendanceRecordSerializer(data=request.data)
        serializer.is_valid(raise_exception=True)

        application = serializer.validated_data['application']
        if application.job_id != job.id or application.status != 'accepted':
            return Response({
                'error': 'Attendance can only be recorded for accepted workers on this job'
            }, status=status.HTTP_400_BAD_REQUEST)

        attendance, created = AttendanceRecord.objects.update_or_create(
            application=application,
            date=serializer.validated_data['date'],
            defaults={
                'status': serializer.validated_data['status'],
                'notes': serializer.validated_data.get('notes', ''),
            },
        )
        output = AttendanceRecordSerializer(attendance)
        return Response(output.data, status=status.HTTP_201_CREATED if created else status.HTTP_200_OK)


@api_view(['GET'])
@permission_classes([IsWorker])
def worker_task_history(request):
    """Return ongoing/completed accepted tasks for the current worker."""
    applications = Application.objects.filter(
        worker=request.user,
        status='accepted',
    ).select_related('job', 'job__employer')

    ongoing = applications.filter(Q(job__completed_at__isnull=True))
    completed = applications.filter(job__completed_at__isnull=False)

    return Response({
        'ongoing': ApplicationSerializer(ongoing, many=True, context={'request': request}).data,
        'completed': ApplicationSerializer(completed, many=True, context={'request': request}).data,
    }, status=status.HTTP_200_OK)


@api_view(['GET'])
@permission_classes([IsWorker])
def worker_task_detail(request, job_id):
    """Show co-workers and attendance for one accepted task."""
    try:
        my_application = Application.objects.select_related('job', 'job__employer').get(
            job_id=job_id,
            worker=request.user,
            status='accepted',
        )
    except Application.DoesNotExist:
        return Response({'error': 'Accepted task not found'}, status=status.HTTP_404_NOT_FOUND)

    coworkers = Application.objects.filter(
        job_id=job_id,
        status='accepted',
    ).select_related('worker').prefetch_related('attendance_records')

    return Response({
        'task': ApplicationSerializer(my_application, context={'request': request}).data,
        'coworkers': TaskCoworkerSerializer(coworkers, many=True).data,
    }, status=status.HTTP_200_OK)


@api_view(['POST'])
@permission_classes([IsEmployerOrAdmin])
def mark_job_completed(request, job_id):
    """Allow employer/admin to mark a job completed once work is done."""
    try:
        job = Job.objects.get(pk=job_id)
    except Job.DoesNotExist:
        return Response({'error': 'Job not found'}, status=status.HTTP_404_NOT_FOUND)

    if job.employer != request.user and request.user.role != 'admin':
        return Response({'error': 'You do not have permission to modify this job'}, status=status.HTTP_403_FORBIDDEN)

    if job.completed_at is None:
        job.completed_at = timezone.now()
        if job.status != 'closed':
            job.status = 'closed'
        job.save(update_fields=['completed_at', 'status', 'updated_at'])
        _issue_completion_certificates(job)

    return Response({
        'message': 'Job marked as completed',
        'job': JobListSerializer(job, context={'request': request}).data,
    }, status=status.HTTP_200_OK)


@api_view(['GET'])
@permission_classes([IsAuthenticated])
def dashboard_summary(request):
    """Small dashboard summary with practical counts for the current user."""
    user = request.user

    if user.role == 'worker':
        accepted = Application.objects.filter(worker=user, status='accepted')
        data = {
            'role': user.role,
            'ongoing_tasks': accepted.filter(job__completed_at__isnull=True).count(),
            'completed_tasks': accepted.filter(job__completed_at__isnull=False).count(),
            'pending_applications': Application.objects.filter(worker=user, status='pending').count(),
            'average_rating': user.reviews_received.aggregate(avg=Avg('rating'))['avg'],
            'reviews_count': user.reviews_received.count(),
        }
    else:
        posted_jobs = Job.objects.filter(employer=user)
        data = {
            'role': user.role,
            'posted_jobs': posted_jobs.count(),
            'active_jobs': posted_jobs.filter(completed_at__isnull=True).count(),
            'completed_jobs': posted_jobs.filter(completed_at__isnull=False).count(),
            'pending_applications': Application.objects.filter(job__employer=user, status='pending').count(),
            'average_rating': user.reviews_received.aggregate(avg=Avg('rating'))['avg'],
            'reviews_count': user.reviews_received.count(),
        }

    return Response(data, status=status.HTTP_200_OK)


class CertificateViewSet(viewsets.ReadOnlyModelViewSet):
    """List certificates for the authenticated user."""

    serializer_class = CertificateSerializer
    permission_classes = [IsAuthenticated]

    def get_queryset(self):
        user = self.request.user
        queryset = Certificate.objects.select_related(
            'recipient', 'job', 'job__employer'
        ).prefetch_related('job__applications__worker')

        if user.role == 'admin':
            return queryset
        return queryset.filter(recipient=user)


@api_view(['GET'])
@permission_classes([IsAuthenticated])
def download_certificate(request, certificate_id):
    try:
        certificate = Certificate.objects.select_related('recipient').get(pk=certificate_id)
    except Certificate.DoesNotExist:
        return Response({'error': 'Certificate not found'}, status=status.HTTP_404_NOT_FOUND)

    if request.user.role != 'admin' and certificate.recipient != request.user:
        return Response({'error': 'You do not have permission to access this certificate'}, status=status.HTTP_403_FORBIDDEN)

    response = HttpResponse(certificate.body_text, content_type='text/plain; charset=utf-8')
    response['Content-Disposition'] = f'attachment; filename="{certificate.certificate_number}.txt"'
    return response
